from setuptools import setup, find_packages

setup(
    name="anomallm",
    version="0.1.0",
    description="Explainable Anomaly Detection SDK for Multivariate Time Series using LLMs",
    author="Hackathon Team",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "pandas>=1.5.0",
        "numpy>=1.20.0",
        "scikit-learn>=1.0",
        "statsmodels>=0.13.0",
        "networkx>=2.6",
        "openai>=1.0.0",
        "chainlit>=1.0.0",
        "fastapi",
        "langchain-core",
        "langchain-groq",
        "langgraph",
        "groq",
        "sqlalchemy",
        "xgboost",
        "optuna",
        "matplotlib",
        "seaborn",
        "python-dotenv",
        "fpdf",
        "kaggle",
        "huggingface_hub",
        "datasets",
        "requests",
        "pydantic>=2.0.0",
        "shap>=0.45.0",
        "lime>=0.2.0.1",
        "imbalanced-learn>=0.12.0",
    ],
    python_requires=">=3.8",
)
